In [1]:
import numpy as np

a= np.array([1,2,3,4,5,])
a

array([1, 2, 3, 4, 5])

Vectorization


In [11]:
import time
import numpy as np
a= np.random.rand(10000000)
b =np.random.rand(10000000)
tic = time.time()
c= np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version1:" + str(1000*(toc-tic))+"ms")

c= 0
tic= time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc =time.time()
print("for loop:" +str(1000*(toc-tic))+"ms")

2499518.650929031
vectorized version1:9.979009628295898ms
for loop:7674.012899398804ms


In [10]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
      [1.2, 104.0, 52.0,8.0],
      [1.8,135.0,99.0,0.9]])
A
cal= A.sum(axis=0) #asix=0 means it will sum it vertically and axis=1 will sum it horizontally
cal
percentage=100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [14]:
import numpy as np
a = np.random.randn(5) #this creates 5 random gaussian variable
print(a)
a.shape
print(a.T)
print(np.dot(a,a.T))

[-1.84656451  0.90490425 -0.70933306 -0.3645345  -0.16217816]
[-1.84656451  0.90490425 -0.70933306 -0.3645345  -0.16217816]
4.890992727282198


In [18]:
a=np.random.randn(5,3)
a
print(a.T)
print(np.dot(a,a.T))

[[-1.54001225 -1.53982969 -0.56904213 -0.15793589  0.67396492]
 [ 0.37021959  0.95950722  0.3293238   0.69810777  1.55478332]
 [-0.21595014  1.67135974 -0.29171886  0.70876057 -0.55053784]]
[[ 2.55533475  2.3656546   1.06125071  0.34861943 -0.34341426]
 [ 2.3656546   6.08517295  0.70464937  2.0976277  -0.46611215]
 [ 1.06125071  0.70464937  0.51736301  0.11301685  0.289115  ]
 [ 0.34861943  2.0976277   0.11301685  1.01463975  0.58876355]
 [-0.34341426 -0.46611215  0.289115    0.58876355  3.17467181]]


In [20]:
a=np.array([[1,1],[1,-1]])
b=np.array([[2],[3]])
c=a+b
c

array([[3, 3],
       [4, 2]])

In [33]:
a = np.random.randn(1288,150)
b=np.random.randn(150,45)
#c=np.dot(a,b)
print(c.shape)

(3, 4)


In [34]:
a=np.random.randn(4,3)
b=np.random.randn(1,3)
c=a*b
print(c.shape)

(4, 3)


In [35]:
a= np.array([[2,1],[1,3]])
c=np.dot(a,a)
c

array([[ 5,  5],
       [ 5, 10]])

In [40]:
def image2vector(image):
    v = image.reshape((image.shape[0] * image.shape[1]* image.shape[2],1))
    return v  

t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(t_image)))



image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [2]:
import numpy as np
x=np.random.randn(4,5)
y=np.sum(x, axis=1)
print(y.shape)

(4,)
